# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('zip_code', models.IntegerField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=20)),
                ('mail', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Devis_Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('price', models.IntegerField(max_length=20)),
                ('quantity', models.IntegerField(max_length=20)),
                ('id_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturier.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=20)),
                ('stock', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=50)),
                ('mdp', models.CharField(max_length=100)),
                ('id_devis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturier.Devis_Facture')),
            ],
        ),
        migrations.AddField(
            model_name='devis_facture',
            name='id_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturier.Product'),
        ),
    ]
