# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0002_auto_20181002_0843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateurs',
            new_name='Utilisateur',
        ),
    ]
