# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0003_auto_20181002_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='slug',
            field=models.CharField(default='plop', max_length=100),
            preserve_default=False,
        ),
    ]
