# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-02 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0004_auto_20181002_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='id_devis',
        ),
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
