# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0004_auto_20181018_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotebill',
            name='transitions',
        ),
    ]
