# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0005_remove_quotebill_transitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotebill',
            name='is_bill',
            field=models.BooleanField(default=False),
        ),
    ]
