# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0005_auto_20181002_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='label',
        ),
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.CharField(default='plop', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='plop', max_length=100),
            preserve_default=False,
        ),
    ]
