# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0006_quotebill_is_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='plop@plop.plop', max_length=50),
            preserve_default=False,
        ),
    ]
