# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-04 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0006_auto_20181004_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Name',
            new_name='name',
        ),
    ]
