# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0007_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='mail',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
