# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 07:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0007_auto_20181004_1208'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Devis_Facture',
            new_name='Quote_Bill',
        ),
    ]
