# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0008_auto_20181029_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'permissions': (('read_client', 'Can see the client detail'),)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('read_product', 'Can see product detail'),)},
        ),
        migrations.AlterModelOptions(
            name='quotebill',
            options={'permissions': (('read_client', 'Can see the client detail'), ('send_quotebill', 'Can send an email'))},
        ),
    ]
