# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0022_auto_20181005_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.SlugField(max_length=100),
        ),
    ]
