# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0023_auto_20181008_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='label',
            new_name='slug',
        ),
    ]
