# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0024_auto_20181008_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('en-cours', 'en-cours'), ('en retard', 'en-retard')], default='en-cours', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='QuoteBill',
            new_name='Quote',
        ),
        migrations.RenameField(
            model_name='ligne',
            old_name='quoteBill',
            new_name='quote',
        ),
        migrations.AddField(
            model_name='bill',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='facturier.Quote'),
        ),
    ]
