# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0025_auto_20181008_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='ref',
            field=models.SlugField(default='.', max_length=100),
            preserve_default=False,
        ),
    ]
