# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0026_quote_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('price', models.IntegerField(max_length=20)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturier.Client')),
            ],
        ),
        migrations.RemoveField(
            model_name='bill',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='client',
        ),
        migrations.RemoveField(
            model_name='ligne',
            name='quote',
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.AddField(
            model_name='ligne',
            name='quoteBill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facturier.QuoteBill'),
        ),
    ]
