# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0027_auto_20181008_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotebill',
            name='price',
        ),
    ]
