# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturier', '0028_remove_quotebill_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotebill',
            name='ref',
            field=models.SlugField(default='plop', max_length=100),
            preserve_default=False,
        ),
    ]
